test:
	sage -python mechanism/binary_randomized_response.py
	sage -python mechanism/discrete_gaussian.py
	sage -python mechanism/discrete_laplace.py
	sage -python policy/histogram_with_aggregator_dp.py
	sage -python policy/multi_hot_histogram_with_client_dp.py
