test:
	sage -python mechanism/symmetric_rappor.py
	# sage -python mechanism/discrete_gaussian.py  # Uncomment it when it is implemented.
	# sage -python mechanism/discrete_laplace.py  # Uncomment it when it is implemented.
	# sage -python policy/histogram_with_aggregator_randomization.py  # Uncomment it when discrete_gaussian.py is implemented.
	sage -python policy/multi_hot_histogram_with_client_randomization.py
