test:
	sage -python mechanism/binary_randomized_response.py
	# sage -python mechanism/discrete_gaussian.py  # Uncomment it when it is implemented.
	# sage -python mechanism/discrete_laplace.py  # Uncomment it when it is implemented.
	# sage -python policy/histogram_with_aggregator_dp.py  # Uncomment it when discrete_gaussian.py is implemented.
	sage -python policy/multi_hot_histogram_with_client_dp.py
